#!/bin/sh

#将tools文件放到当前用户目录下
USER=ding
GROUP=ding
PASSWORD=93177852

DIR_MODE=0755
FILE_MODE=0766

LOG_DIR=/home/$USER/log
HOSTS_FILE=/etc/hosts

CURRENT_DIR=`pwd`
CURRENT_DIR=${CURRENT_DIR%/*}
BIN_DIR=$CURRENT_DIR/src/bin
PHPSO_DIR=$CURRENT_DIR/src/phpso

CONF_DIR=$CURRENT_DIR/conf

BOOT_DIR=$CURRENT_DIR/boot
INSTALL_DIR=$CURRENT_DIR/install

PREFIX_DIR=/usr/local

PACKAGE_DIR=/home/$USER/src
PROJECT_DIR=/home/$USER/projects
PID_DIR=/tmp/pid
SOCKET_DIR=/tmp/socket
